### ISSUE TITLE
Change license to MPL

### ISSUE THREAD

**Issue by hydroid7** [elkodon/elkodon#62]
Hi,
the code looks promising. However, it is now licensed as GPL.
Would it be possible to change the license to MPL?

I think MPL would allow wide adoption while still ensuring contributions come back to the main source.
Thank you for considering.

**Comment by elfenpiff** [comment]
@hydroid7 at the moment, the project is in a pre-announcement phase. After we have finished all the tasks in #3 we intend to use a dual-license: MIT & Apache 2.0.
GPL-3.0 is just a temporary thing until we have figured all the details out.

So give us two more weeks, then this project will move into eclipse-iceoryx as iceoryx-ng, and I will ping you first!

**Comment by hydroid7** [comment]
Hi @elfenpiff ,
thank you for your response and insights. I'm glad to hear you intentions and look forward.
